### ISSUE TITLE
Add a License

### ISSUE THREAD

**Issue by Bad-Science** [drakecsmall/RemoteAcademy#1]
Title says it all! Has the existing team discussed what license they would like to use?

**Comment by drakewashere** [comment]
Based on the fact the original creators are no longer active, and RPI has ownership of the project, we may want to err on the side of as permissive a license as possible for use, limit liability / warranty, and maintain ownership.

I would say MIT License.

**Comment by drakewashere** [comment]
I have opened pull requests for using MIT License as well as an extension there of, the ABSAJ License

**Comment by Bad-Science** [comment]
I would suggest sticking with the MIT License. I don't believe the ABSAJ License is OSI approved 😛

**Comment by drakewashere** [comment]
I am going to leave it there in case anyone wants it. It's not OSI approved but neither is breathing so :man_shrugging:
